# Generated by Django 5.2.5 on 2025-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='q_hint_text',
            field=models.CharField(default='No hint available', max_length=500),
        ),
    ]
